name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
    - name: Run Tests
      run: |
        export GOFLAGS=-mod=vendor
        export GO111MODULE=on
        go mod download
        go mod vendor
        go mod verify
        go test -v
        
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile.deploy --tag juanchiriera/sre-challange:$(date +%s)
    - name: Publish Docker image
      run: docker push juanchiriera/sre-challange
    
  
  
