name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
      - name: Test Application
        run: go test -v
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.deploy --tag juanchiriera/sre-challange:$(date +%s)
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker image
      run: docker push juanchiriera/sre-challange:$(date +%s)
  
  
