name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.deploy --tag juanchiriera/sre-challange:$(date +%s)
    - name: Publish Docker image
      run: docker push juanchiriera/sre-challange
    
  
  
